theme: jekyll-theme-cayman
title: [Tonni Das Jui]
description: [I am an PhD student of computer science at Baylor University, USA where I am currently working as both Graduate Research Assistant and Graduate Teaching Assistant. I have completed Bachelor of Sciences in Computer Science and Engineering from BRAC University, Bangladesh.]
